# Generated by Django 3.2.5 on 2022-12-03 17:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20221203_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), null=True, size=8),
        ),
    ]
