# Generated by Django 3.2.5 on 2022-12-03 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='board',
        ),
    ]
