# Generated by Django 3.2.16 on 2022-11-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Скидка'),
        ),
    ]
