# Generated by Django 3.2.5 on 2022-12-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20221130_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='size1',
            field=models.CharField(blank=True, choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXl')], max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='size2',
            field=models.CharField(blank=True, choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXl')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size3',
            field=models.CharField(blank=True, choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXl')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size4',
            field=models.CharField(blank=True, choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXl')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size5',
            field=models.CharField(blank=True, choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXl')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='RatingStar',
        ),
    ]
