# Generated by Django 3.2.5 on 2022-12-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20221203_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='consists_of',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Состоит из'),
        ),
    ]
