# Generated by Django 3.2.5 on 2022-12-02 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_consists_of'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterField(
            model_name='product',
            name='size1',
            field=models.CharField(choices=[('s', 'S / 46-48'), ('m', 'M / 48-50'), ('l', 'L / 50-52'), ('xl', 'XL / 52-54'), ('xxl', 'XXl / 54-56')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size2',
            field=models.CharField(blank=True, choices=[('s', 'S / 46-48'), ('m', 'M / 48-50'), ('l', 'L / 50-52'), ('xl', 'XL / 52-54'), ('xxl', 'XXl / 54-56')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size3',
            field=models.CharField(blank=True, choices=[('s', 'S / 46-48'), ('m', 'M / 48-50'), ('l', 'L / 50-52'), ('xl', 'XL / 52-54'), ('xxl', 'XXl / 54-56')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size4',
            field=models.CharField(blank=True, choices=[('s', 'S / 46-48'), ('m', 'M / 48-50'), ('l', 'L / 50-52'), ('xl', 'XL / 52-54'), ('xxl', 'XXl / 54-56')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size5',
            field=models.CharField(blank=True, choices=[('s', 'S / 46-48'), ('m', 'M / 48-50'), ('l', 'L / 50-52'), ('xl', 'XL / 52-54'), ('xxl', 'XXl / 54-56')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/carousel'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product'),
        ),
    ]
