# Generated by Django 3.2.5 on 2022-11-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
    ]
