# Generated by Django 3.2.5 on 2022-12-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Product_like', 'verbose_name_plural': 'Product_likes'},
        ),
    ]
